# Generated by Django 3.0.6 on 2020-05-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='blocks')),
            ],
        ),
    ]
